// Shared player roster backed by Vercel KV / Upstash Redis.
// One person = one id, and the id is the only thing anything else ever stores.
// Names and skill levels live here and nowhere else, so renaming someone is a single
// write to a single field — nothing downstream (today's session, the announced plan)
// holds a copy that can go stale and come back to life as a second person.
// Ids are generated by the client so a phone with no signal can still add someone and
// push the same id later; the server only checks the shape.
// No npm dependencies — talks to the Upstash REST API with plain fetch, so drag-and-drop deploys work.

const KEY = "badminton:people";
// Pre-id storage, read once to migrate and then left alone (a rollback still finds it).
const OLD_KEY = "badminton:roster";
const OLD_LKEY = "badminton:levels";
const MAX_NAME = 20;
const MAX_PEOPLE = 200;
const ID_RE = /^[A-Za-z0-9_-]{1,32}$/;
const LEVELS = ["RK", "BG-", "BG+", "NB", "N", "S"];
// Levels stored under an older scale (Rookie, BG1 / BG2, and before that BG / S- / S / N / P- / P / P+)
// map onto the current one on read, so an existing roster keeps its levels instead of
// falling back to "no level".
const LEVEL_ALIAS = { Rookie: "RK", BG1: "BG-", BG2: "BG+", BG: "BG-", "S-": "BG+", S: "NB", N: "N", "P-": "S", P: "S", "P+": "S" };

function creds() {
  const url = process.env.KV_REST_API_URL || process.env.UPSTASH_REDIS_REST_URL;
  const token = process.env.KV_REST_API_TOKEN || process.env.UPSTASH_REDIS_REST_TOKEN;
  if (!url || !token) return null;
  return { url: String(url).replace(/\/+$/, ""), token: String(token) };
}

async function redis(c, parts) {
  const path = parts.map(encodeURIComponent).join("/");
  const r = await fetch(`${c.url}/${path}`, { headers: { Authorization: `Bearer ${c.token}` } });
  if (!r.ok) throw new Error(`upstash ${r.status}`);
  const j = await r.json();
  return j.result;
}

function cleanName(raw) {
  const name = String(raw == null ? "" : raw).replace(/[ -]/g, "").trim();
  return name.length && name.length <= MAX_NAME ? name : null;
}

function cleanId(raw) {
  const id = String(raw == null ? "" : raw).trim();
  return ID_RE.test(id) ? id : null;
}

// "-" / "" both mean "no level yet".
function cleanLevel(raw) {
  const lv = String(raw == null ? "" : raw).trim();
  if (!lv || lv === "-") return "";
  if (LEVELS.indexOf(lv) >= 0) return lv;
  return LEVEL_ALIAS[lv] || null;
}

// hgetall comes back as a flat [field, value, field, value, ...] array.
function pairsToObject(flat) {
  const out = {};
  if (!Array.isArray(flat)) return out;
  for (let i = 0; i + 1 < flat.length; i += 2) out[flat[i]] = flat[i + 1];
  return out;
}

function parsePerson(id, raw) {
  let v = raw;
  if (typeof v === "string") { try { v = JSON.parse(v); } catch (e) { v = { name: raw }; } }
  if (!v || typeof v !== "object") return null;
  const name = cleanName(v.name);
  if (!name) return null;
  return { id, name, level: cleanLevel(v.level) || "" };
}

function newId() {
  return "p" + Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
}

// Pre-id rosters kept names in a SET and levels in a HASH keyed by name. Mint an id for
// each name once, the first time a new client asks for the roster.
async function migrate(c) {
  const [names, levelPairs] = await Promise.all([
    redis(c, ["smembers", OLD_KEY]),
    redis(c, ["hgetall", OLD_LKEY]),
  ]);
  if (!Array.isArray(names) || !names.length) return [];
  const levels = pairsToObject(levelPairs);
  const people = [];
  const args = ["hset", KEY];
  names.forEach((raw) => {
    const name = cleanName(raw);
    if (!name) return;
    const person = { id: newId(), name, level: cleanLevel(levels[raw]) || "" };
    people.push(person);
    args.push(person.id, JSON.stringify({ name: person.name, level: person.level }));
  });
  if (people.length) await redis(c, args);
  return people;
}

async function readPeople(c) {
  const flat = await redis(c, ["hgetall", KEY]);
  const obj = pairsToObject(flat);
  const ids = Object.keys(obj);
  if (!ids.length) return migrate(c);
  return ids.map((id) => parsePerson(id, obj[id])).filter(Boolean);
}

function snapshotOf(people) {
  const list = people.slice().sort((a, b) => a.name.localeCompare(b.name, "th"));
  return { ok: true, people: list };
}

async function snapshot(c) {
  return snapshotOf(await readPeople(c));
}

async function writePerson(c, person) {
  await redis(c, ["hset", KEY, person.id, JSON.stringify({ name: person.name, level: person.level })]);
}

function readBody(req) {
  if (!req.body) return {};
  if (typeof req.body === "string") { try { return JSON.parse(req.body); } catch (e) { return {}; } }
  return req.body;
}

module.exports = async (req, res) => {
  res.setHeader("Cache-Control", "no-store");

  const c = creds();
  if (!c) {
    res.status(503).json({ ok: false, reason: "not-configured" });
    return;
  }

  try {
    if (req.method === "GET") {
      res.status(200).json(await snapshot(c));
      return;
    }

    if (req.method === "POST") {
      const body = readBody(req);
      const action = body.action;

      if (action === "reset") {
        await redis(c, ["del", KEY]);
        await redis(c, ["del", OLD_KEY]);        // ไม่ลบด้วย migrate จะดึงชื่อเก่ากลับมาทั้งชุด
        await redis(c, ["del", OLD_LKEY]);
        res.status(200).json({ ok: true, people: [] });
        return;
      }

      if (action === "add" || action === "remove" || action === "level" || action === "rename") {
        const people = await readPeople(c);
        // Older clients addressed people by name; resolve so a stale tab can't edit the wrong row.
        const byId = {};
        const byName = {};
        people.forEach((p) => { byId[p.id] = p; byName[p.name] = p; });
        const wanted = cleanId(body.id);
        const target = (wanted && byId[wanted]) || (cleanName(body.name) ? byName[cleanName(body.name)] : null);

        if (action === "add") {
          const name = cleanName(body.name);
          if (!name) { res.status(400).json({ ok: false, reason: "bad-name" }); return; }
          const level = cleanLevel(body.level);
          if (level === null) { res.status(400).json({ ok: false, reason: "bad-level" }); return; }
          const dup = byName[name];
          if (dup) {                              // ชื่อซ้ำ = คนเดิม ไม่ใช่คนใหม่ (สองเครื่องกดพร้อมกันก็ได้แถวเดียว)
            if (level && !dup.level) { dup.level = level; await writePerson(c, dup); }
            res.status(200).json(snapshotOf(people));
            return;
          }
          if (people.length >= MAX_PEOPLE) { res.status(409).json({ ok: false, reason: "roster-full" }); return; }
          const person = { id: wanted || newId(), name, level: level || "" };
          if (byId[person.id]) { res.status(409).json({ ok: false, reason: "id-taken" }); return; }
          await writePerson(c, person);
          people.push(person);
          res.status(200).json(snapshotOf(people));
          return;
        }

        if (!target) { res.status(200).json(snapshotOf(people)); return; }   // ไม่มีคนนี้แล้ว = สำเร็จโดยปริยาย

        if (action === "remove") {
          await redis(c, ["hdel", KEY, target.id]);
          res.status(200).json(snapshotOf(people.filter((p) => p.id !== target.id)));
          return;
        }

        if (action === "level") {
          const level = cleanLevel(body.level);
          if (level === null) { res.status(400).json({ ok: false, reason: "bad-level" }); return; }
          target.level = level;
          await writePerson(c, target);
          res.status(200).json(snapshotOf(people));
          return;
        }

        // rename — the reason ids exist. One field, one write, everything downstream follows.
        const next = cleanName(body.to != null ? body.to : body.newName);
        if (!next) { res.status(400).json({ ok: false, reason: "bad-name" }); return; }
        const clash = byName[next];
        if (clash && clash.id !== target.id) { res.status(409).json({ ok: false, reason: "name-taken" }); return; }
        target.name = next;
        await writePerson(c, target);
        res.status(200).json(snapshotOf(people));
        return;
      }

      res.status(400).json({ ok: false, reason: "bad-action" });
      return;
    }

    res.setHeader("Allow", "GET, POST");
    res.status(405).json({ ok: false, reason: "method" });
  } catch (err) {
    res.status(502).json({ ok: false, reason: "upstream", detail: String(err.message || err) });
  }
};
